name: t0-typescript-action
description:
  Download failed workflow artifacts, emit their contents, and prepare for
  automated diagnosis.
author: shuyangli

branding:
  icon: alert-circle
  color: orange

inputs:
  token:
    description: GitHub token used to query workflow run artifacts.
    required: true
  workflow:
    description: The github workflow event.
    required: false
  artifacts-dir:
    description: The directory to store the artifacts.
    required: false
    default: 'artifacts'

outputs: {}

runs:
  using: node24
  main: dist/index.js
