name: create-pr-feedback
description: Prepare and surface pull request feedback from workflow data.
author: shuyangli

branding:
  icon: compose
  color: blue

runs:
  using: node24
  main: ../dist/create-pr-feedback/index.js
