name: create-pr-feedback
description: Prepare and surface pull request feedback from workflow data.
author: shuyangli

branding:
  icon: compose
  color: blue

inputs:
  tensorzero-base-url:
    description: Base URL for the TensorZero instance.
    required: true
  clickhouse-url:
    description:
      URL for ClickHouse HTTP interface, in the format of
      http[s]://[username:password@]hostname:port[/database].
    required: true
  clickhouse-table:
    description: Table for the PR to inference mapping.
    required: true
  output-artifacts-dir:
    description: Directory to store output artifacts for debugging purposes.

outputs:
  feedback-body:
    description: The feedback body that was generated for downstream steps.

runs:
  using: node24
  main: ../dist/create-pr-feedback/index.js
