name: generate-pr-patch
description:
  Download failed workflow artifacts, emit their contents, and prepare for
  automated diagnosis.
author: shuyangli

branding:
  icon: alert-circle
  color: orange

inputs:
  token:
    description: GitHub token used to query workflow run artifacts.
    required: true
  tensorzero-base-url:
    description: Base URL for the TensorZero instance.
    required: true
  diff-summary-path:
    description: File path for diff summary.
    required: true
  full-diff-path:
    description: File path for full diff.
    required: true
  input-logs-dir:
    description: Directory containing workflow failure logs.
    required: true
  output-artifacts-dir:
    description: Directory to store output artifacts for debugging purposes.
  clickhouse-url:
    description:
      Base URL for ClickHouse HTTP interface (e.g. https://<host>:8443/).
  clickhouse-table:
    description: Table where inference to PR associations should be recorded.
  clickhouse-username:
    description: Username for ClickHouse basic authentication.
  clickhouse-password:
    description: Password for ClickHouse basic authentication.
  clickhouse-database:
    description: Database that contains the ClickHouse table.

outputs:
  comment:
    description: The comment string that will be posted to the PR
  pull-request-patch:
    description: The patch string that will be generated in a new pull request

runs:
  using: node24
  main: ../dist/generate-pr-patch/index.js
