name: generate-pr-patch
description:
  Download failed workflow artifacts, emit their contents, and prepare for
  automated diagnosis.
author: shuyangli

branding:
  icon: alert-circle
  color: orange

inputs:
  token:
    description: GitHub token used to query workflow run artifacts.
    required: true
  tensorzero-base-url:
    description: Base URL for the TensorZero instance.
    required: true
  diff-summary-path:
    description: File path for diff summary.
    required: true
  full-diff-path:
    description: File path for full diff.
    required: true
  input-logs-dir:
    description: Directory containing workflow failure logs.
    required: true
  output-artifacts-dir:
    description: Directory to store output artifacts for debugging purposes.

outputs:
  comment:
    description: The comment string that will be posted to the PR

runs:
  using: node24
  main: ../dist/generate-pr-patch/index.js
