name: Provide Pull Request Feedback to CI Bot

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  create-pr-feedback:
    runs-on: ubuntu-latest
    name: Create PR Feedback
    steps:
      - name: Write TensorZero metrics configuration
        run: |
          echo "[functions.tensorzero_github_ci_bot]" > tensorzero.toml
          echo "type = \"chat\"" >> tensorzero.toml
          echo "" >> tensorzero.toml
          echo "[functions.tensorzero_github_ci_bot.variants.gpt_5]" >> tensorzero.toml
          echo "type = \"chat_completion\"" >> tensorzero.toml
          echo "model = \"openai::gpt-5\"" >> tensorzero.toml
          echo "" >> tensorzero.toml
          echo "[metrics.tensorzero_github_ci_bot_pr_merged]" >> tensorzero.toml
          echo "type = \"boolean\"" >> tensorzero.toml
          echo "optimize = \"max\"" >> tensorzero.toml
          echo "level = \"inference\"" >> tensorzero.toml
          echo "[metrics.tensorzero_github_ci_bot_diff_patched_successfully]" >> tensorzero.toml
          echo "type = \"boolean\"" >> tensorzero.toml
          echo "optimize = \"max\"" >> tensorzero.toml
          echo "level = \"inference\"" >> tensorzero.toml

      - name: Start TensorZero gateway
        run: |
          docker pull tensorzero/gateway:latest
          docker run -d --rm \
            --name tensorzero-gateway \
            -e TENSORZERO_CLICKHOUSE_URL=${{ secrets.CLICKHOUSE_URL }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -p 3000:3000 \
            --volume ./:/app \
            tensorzero/gateway:latest --config-file /app/tensorzero.toml

          for i in {1..20}; do
            curl -fsS http://localhost:3000/health && exit 0
            sleep 3
          done
          echo "Gateway never became ready" >&2
          exit 1

      - name: Send PR Feedback
        uses: ./create-pr-feedback@main
        with:
          tensorzero-base-url: http://localhost:3000
          tensorzero-pr-merged-metric-name: tensorzero_github_ci_bot_pr_merged
          clickhouse-url: ${{ secrets.CLICKHOUSE_URL }}
          clickhouse-table: GitHubBotPullRequestToInferenceMap

      - name: Stop TensorZero gateway
        if: always()
        run: docker stop tensorzero-gateway
        continue-on-error: true