name: Run Pytest

on:
  pull_request:
    branches: ["main"]

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 'latest'

      - name: Run Test
        run: npm test
